name: Advent Calendar Door Opener - Daily from Dec 1 to Dec 25
on:
  schedule:
    - cron: '0 0 1-25 12 *'  # Runs every day from Dec 1 to Dec 25 at midnight
  workflow_dispatch:  # Allows manual triggering of the workflow
    inputs: 
      year: 
        description: 'Jahr'
        required: true 
      day: 
        description: 'Tag'
        required: true

jobs:
  create-advent-day:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set date variables 
        id: set-date 
        run: | 
          if [ -z "${{ github.event.inputs.year }}" ]; then 
            echo "year=$(date +'%Y')" >> $GITHUB_ENV 
          else 
            echo "year=${{ github.event.inputs.year }}" >> $GITHUB_ENV 
          fi 
          if [ -z "${{ github.event.inputs.day }}" ]; then 
            echo "day=$(date +'%d')" >> $GITHUB_ENV 
          else 
            echo "day=${{ github.event.inputs.day }}" >> $GITHUB_ENV 
          fi
          
      - name: Create the new Advent Day
        run: .\create-advent-day.ps1 ${{ env.year }} ${{ env.day }}
        shell: pwsh
        
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions' 
          git config --global user.email 'github-actions@github.com'
          $currentDate = Get-Date -Format "dd. MMMM"
          git add .
          git commit -m "Automated commit for new Advent Day on $currentDate"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}